# Generated by Django 5.2.1 on 2025-05-30 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogsLevelThree",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("body", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="blogslevelone",
            options={"ordering": ["created_at"]},
        ),
        migrations.AlterModelOptions(
            name="blogsleveltwo",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="blogsmaxclearance",
            options={"ordering": ["-created_at"]},
        ),
    ]
