# Generated by Django 5.2.1 on 2025-05-30 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(default="none", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customuser",
            name="last_name",
            field=models.CharField(default="none", max_length=100),
            preserve_default=False,
        ),
    ]
